server:
  port: 8091

spring:
  application:
    name: web2
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8081/eureka,http://user:password123@localhost:8082/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



#http://localhost:8090/hystrix
#http://localhost:8090/actuator/hystrix.stream