server:
  port: 7910
  
user: 
  userServicePath: http://localhost:7900/simple/
  
spring:  application:    name: microservice-provider-movie  
  
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    
feign:
  hystrix:
    enabled: true