server:
  port: 7940
  
spring:
  application:
    name: microservice-gateAway-Zuul
  
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
    users:
      path: /myusers/**
      url: http://172.21.224.1:7901